### ISSUE TITLE
Please review User Auth feature.

### ISSUE THREAD

**Issue by mochimaster** [mochimaster/Etsyc#2]
Hi Elliot,

I went through your checklist and able to complete the list except:
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
and 
- [ ] Errors should clear when moving between `/signup` and `/login`.

I will try to complete this on the train tomorrow / get help .

Thanks
Kee

**Comment by mochimaster** [comment]
My heroku deployment is still failing as of 10/12 9.13AM. 

Please disregard this issue for now.

I will update this thread once I can get the deployment to success.

**Comment by mochimaster** [comment]
Hi Elliot, I have deployed the latest code to Heroku and it is ready for review.

**Comment by evhumphrey** [comment]
- [ ] Can you update the heroku link on your wiki https://github.com/mochimaster/Etsyc/wiki
